apiVersion: v1
kind: Namespace
metadata:
  name: test

---

# ServiceAccount for the SPIRE agent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: npipe-server
  namespace: test

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npipe-server
  namespace: test
  labels:
    app: npipe-server
spec:
  selector:
    matchLabels:
      app: npipe-server
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: test
      labels:
        app: npipe-server
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: npipe-server
      containers:
        - name: npipe-server
          image: marcosdy/npipe-server:ltsc2019
          volumeMounts:
            - name: server-named-pipe
              mountPath: \\.\pipe\wservice
              readOnly: false
          # livenessProbe:
            # httpGet:
              # path: /live
              # port: 8080
            # initialDelaySeconds: 10
            # periodSeconds: 10
          # readinessProbe:
            # httpGet:
              # path: /ready
              # port: 8080
            # initialDelaySeconds: 10
            # periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
        - name: server-named-pipe
          hostPath:
            path: \\.\pipe\wservice
            # TODO: what type must we use?
            type: null

